### ISSUE TITLE
Is it possible to show an example with network_rulesets

### ISSUE THREAD

**Issue by hisathya** [avinor/terraform-azurerm-event-hubs#1]
I liked your module structure. I am new bee and working on to get the event hub module created. Consider it more of an enhancement for what you got already. 

I have got bunch of network_rulesets but only with 'ip_rule' but not 'virtual_network_rule'. 

You got code already in main.tf. Can you please show an example with 'ip_rule' if you are okay with it ?

I am also struggling with 'disaster_recovery_config' option which needs to be enabled only for prod env. 

https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace_disaster_recovery_config.html

**Comment by yngveh** [comment]
This repo is now longer maintained, closing issue
