### ISSUE TITLE
Remove Provider Configuration

### ISSUE THREAD

**Issue by rsilva-rs** [avinor/terraform-azurerm-event-hubs#9]
We are encountering issues when sourcing this public module in our deployment as there is a [provider configuration defined in the main.tf file](https://github.com/avinor/terraform-azurerm-event-hubs/blob/v2.0.0/main.tf#L11). With Terraform v0.13 it is recommended to remove provider blocks from your module definitions. Please refer to the following document below for more information:

https://www.terraform.io/docs/language/modules/develop/providers.html#legacy-shared-modules-with-provider-configurations

**Comment by yngveh** [comment]
This repo is no longer maintained, closing issue.
